# Generated by Django 4.2.7 on 2025-12-19 18:18

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='otp_codes_phone_n_54cfd5_idx',
            old_name='otp_codes_phone_n_created_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='otp_codes_phone_n_dba476_idx',
            old_name='otp_codes_phone_n_purpose_is_used_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_phone_n_a3b1c5_idx',
            old_name='users_phone_n_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_created_6541e9_idx',
            old_name='users_created_idx',
        ),
    ]
